#!/usr/bin/env bash

SHADOW_OFFSET="6,6"
TEXT_OFFSET="5,5"
FONT="/System/Library/Fonts/HelveticaNeue.ttc"
POINTSIZE=12

caption() {
  local outfile="$1"
  local text="$2"
  local infile="originals/${outfile}"

  if [ ! -e "$outfile" ]; then
    ensure_directories "$outfile"
    make_caption "$infile" "$text" "$outfile"
  fi
}

ensure_directories() {
  dir=$(dirname "$1")
  mkdir -p "$dir"
}

make_caption() {
  local infile="$1"
  local text="$2"
  local outfile="$3"

  gm convert "$infile" \
    -font $FONT -pointsize $POINTSIZE \
    -gravity southwest \
    -fill black -draw "text $SHADOW_OFFSET \"$text\"" \
    -fill white -draw "text $TEXT_OFFSET \"$text\"" \
    "$outfile"
}

winter() {
  caption 1-winter/andreea-chidu-234595.jpg 'Lake Louise — Alberta, Canada'
  caption 1-winter/bachalpsee-mountains.jpg 'Bachalpsee Lake — Grindelwald, Switzerland'
  caption 1-winter/blue-morning.jpg 'Sulqan — Tehran, Iran'
  caption 1-winter/emerald-bay.jpg 'Emerald Bay, Lake Tahoe — California'
  caption 1-winter/first-light-of-winter.jpg 'Kootenay River — British Columbia, Canada'
  caption 1-winter/loch-annaachlaise.jpg 'Lochan na Achlaise — Glencoe, Scotland'
  caption 1-winter/morning-mist.jpg 'Mt. Rainier — Washington'
  caption 1-winter/mount-cook.jpg 'Mount Cook — New Zealand'
  caption 1-winter/mount-fuji.jpg 'Mt. Fuji — Honshū, Japan'
  caption 1-winter/nightfall-at-lake-aurora.jpg 'Composite — Bannalpsee, Switzerland & Iceland Sky'
  caption 1-winter/riffelsee.jpg 'Riffelsee — Zermatt, Switzerland'
  caption 1-winter/sea-of-clouds.jpg 'Rigi Mountains — Switzerland'
  caption 1-winter/the-salton-sea.jpg 'Salton Sea — California'
  caption 1-winter/svalbard-coast.jpg 'Svalbard? — Norway'
}

spring() {
  caption 2-spring/abavariansunset.jpg 'Schrecksee — South Germany — 47.4386, 10.4652'
  caption 2-spring/coloursofmiddleearth.jpg 'Lake Wakatipu — New Zealand'
  caption 2-spring/glow-behind-hood.jpg 'Mount Hood — Portland, Oregon'
  caption 2-spring/grampiansdawn.jpg 'Lake Fyans — Victoria, Australia'
  caption 2-spring/iceland-sunset.jpg 'Vik — Iceland'
  caption 2-spring/lake-te-anau-downs.jpg 'Lake Te Anau Downs — New Zealand — Ryan Hunt'
  caption 2-spring/light-and-rain.jpg 'Highway 285 South — New Mexico'
  caption 2-spring/lonelyisland.jpg 'Phi Phi Islands — Thailand'
  caption 2-spring/lonesome-shepherd.jpg 'Alborz Mountains — Damavand, Iran'
  caption 2-spring/milford-sound.jpg 'Milford Sound — New Zealand — Ryan Hunt'
  caption 2-spring/misty-sunrise.jpg 'Kardzhali Dam — Bulgaria'
  caption 2-spring/pureness.jpg 'Tar Lake — Damavand, Iran'
  caption 2-spring/risingmountains.jpg 'Sefid Rud — Chalus Pass, Iran'
  caption 2-spring/thecobbler.jpg 'The Cobbler — Southern Highlands, Scotland'
  caption 2-spring/theforest.jpg 'Northern California'
}

summer() {
  caption 3-summer/alta-quiet-sunset.jpg 'Alta — Norway — 69.9614, 23.2414'
  caption 3-summer/blue-illumination.jpg 'Newcastle — New South Wales, Australia'
  caption 3-summer/chicago-from-indiana.jpg 'Chicago from Indiana'
  caption 3-summer/clouds.jpg 'Above Bohol — Philippines'
  caption 3-summer/glacier-point-sunset.jpg 'Glacier Point — Yosemite, California'
  caption 3-summer/grandtetonsunset.jpg 'Grand Teton National Park, Wyoming'
  caption 3-summer/hauraki-golf.jpg 'Hauraki Gold — New Zealand — Ryan Hunt'
  caption 3-summer/hautes-pyrenees.jpg 'Hautes-Pyrénées — Ris, France'
  caption 3-summer/ithilien.jpg 'Tongariro National Park — New Zealand'
  caption 3-summer/milford-sound-sunrise.jpg 'Milford Sound — New Zealand — -44.671545, 167.926841'
  caption 3-summer/pagview.jpg 'Pag Island — Croatia'
  caption 3-summer/pastel-tides.jpg 'Sandy Beach — Oahu, Hawaii'
  caption 3-summer/reflection-on-the-lake.jpg 'Lake Pukaki — New Zealand'
  caption 3-summer/riomaggiore-sunset.jpg 'Riomaggiore — Liguria Region, Italy'
  caption 3-summer/sassolungo.jpg 'Sassolungo — Seceda, Italy'
  caption 3-summer/sunriseinwhitby.jpg 'Whitby Harbour, U.K.'
  caption 3-summer/the-4am-campfire.jpg 'Beautiful Sword River — Vyazovo, Russia'
  caption 3-summer/the-western-divide.jpg 'Moro Rock — Sequoia National Park, California'
  caption 3-summer/whitesandsnationalmonument.jpg 'White Sands National Monument, New Mexico'
}

fall() {
  caption 4-fall/alpen-gluhenii.jpg 'Kampenwand — South Germany — 47.7552, 12.3570'
  caption 4-fall/break-of-dawn.jpg 'Nowhere'
  caption 4-fall/crawling-over-portland.jpg 'Pittock Mansion — Portland, Oregon'
  caption 4-fall/darkness-across.jpg 'Paulina Lake — Oregon'
  caption 4-fall/dull-sunset.jpg 'Schauinsland Mountain — Freiburg, Germany'
  caption 4-fall/firstbeams.jpg 'Alborz Mountains — Iran'
  caption 4-fall/hakone-fuji-sunset.jpg 'Mount Fuji, Lake Ashi — Hakone, Japan — 35.2023, 139.0306'
  caption 4-fall/hautespyrenees.jpg 'Hautes-Pyrénées — Ris, France'
  caption 4-fall/heaven-and-earth.jpg 'Sanctuary of San Salvador — Mallorca, Balearic Islands, Spain'
  caption 4-fall/hollental.jpg 'Höllentalklamm — Zugspitze — Germany'
  caption 4-fall/kungsleden.jpg 'Kungsleden Trail — Swedish Lapland — Stepan Kuklik'
  caption 4-fall/kvalavag.jpg 'Boathouse — Kvalavåg, Norway'
  caption 4-fall/loneguardian.jpg "O'Briens Tower — Cliffs Of Moher, Ireland"
  caption 4-fall/milkywayoverathawingbowlake.jpg 'Bow Lake — Banff National Park, Alberta, Canada — 51.6780, -116.4640'
  caption 4-fall/mountain-silhouette.jpg 'Olympic Mountains — Seattle, Washington'
  caption 4-fall/mountcook.jpg 'Mount Cook — New Zealand'
  caption 4-fall/skogafossiceland.jpg 'Skógafoss — Skógá River — Iceland'
  caption 4-fall/sunset-blue-mountain.jpg 'Blue Mountain — Olympic National Park — Washington'
  caption 4-fall/the-eagle.jpg 'Gstaad, Switzerland — 46.4761, 7.2585'
  caption 4-fall/twilightislands.jpg 'Sasebo-city — Nagasaki, Japan'
}

winter
spring
summer
fall
